server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse_db
    username: root
    password: Poorvi@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  jackson:
    serialization:
      indent-output: true

logging:
  level:
    root: INFO
    com.warehouse: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE